### ISSUE TITLE
'External link' icon is wrong colour on first load in dark mode

### ISSUE THREAD

**Issue by kdmcguire** [mbarker84/eleventy-blog#12]
If the first load uses dark mode, the icon for external links is black (on the dark background). After swapping to light mode and back, it's white.

Tested in Firefox and Chrome on Windows.

![image](https://github.com/mbarker84/css-irl-eleventy/assets/2109807/f8b00169-0314-4fd2-a3e5-cbc0eafaf15d)

**Comment by mbarker84** [comment]
Thanks for the feedback @kdmcguire! I’ve just pushed a fix 🙂

**Comment by kdmcguire** [comment]
Nice! That's done the trick 🙂
