### ISSUE TITLE
Parsing error in rss flux

### ISSUE THREAD

**Issue by toinebeg** [mbarker84/eleventy-blog#5]
Hi, 
I tried to add your brilliant blog to my rss feeds but it seems that one of the descriptions break the parsing. 

![css-irl_rssBug](https://user-images.githubusercontent.com/3091094/120628303-d4268500-c464-11eb-87a7-065c7df27b4c.png)

Look like a escaping problem for the single quote.

**Comment by mbarker84** [comment]
Sorry to be so late spotting this open issue! The RSS feed should be working fine now :)
